"""neovim + luasnip: detection, jsregexp build, and the loader plugin file."""

from dataclasses import dataclass
import os
from pathlib import Path
import shutil
import subprocess
import sys

from ..compiler import lua_quote
from ..errors import EditorError
from ..paths import xdg_config_home, xdg_data_home

NOT_FOUND = "nvim not found on PATH"
DEFAULT_FILES = ("tex.lua", "markdown.lua")
SUFFIX = ".lua"
LOADER_MARKER = "generated by `snipsmith init`"

LOADER_TEMPLATE = """\
-- generated by `snipsmith init`; safe to edit or delete.
--
-- loads the luasnip snippet files snipsmith writes to `snippets_dir` the first
-- time a latex or markdown buffer opens. it turns on autosnippets and, if you
-- have not configured one, maps <Tab> in visual mode to store a selection for
-- ${VISUAL} snippets; everything else in your luasnip config is left alone.

local snippets_dir = {snippets_dir}

vim.api.nvim_create_autocmd("FileType", {
  pattern = { "tex", "plaintex", "latex", "markdown" },
  once = true,
  callback = function()
    local ok, ls = pcall(require, "luasnip")
    if not ok then
      vim.notify(
        "snipsmith: luasnip is not installed, so no snippets were loaded",
        vim.log.levels.WARN
      )
      return
    end

    local config = require("luasnip.session").config
    if config == nil then
      ls.setup({ enable_autosnippets = true, store_selection_keys = "<Tab>" })
    else
      local changed = false
      if not config.enable_autosnippets then
        config.enable_autosnippets = true
        changed = true
      end
      if config.cut_selection_keys == nil then
        config.cut_selection_keys = "<Tab>"
        changed = true
      end
      if changed and ls.config._setup then
        ls.config._setup()
      end
    end

    ls.filetype_extend("plaintex", { "tex" })
    require("luasnip.loaders.from_lua").load({ paths = { snippets_dir } })
  end,
})
"""


@dataclass
class Neovim:
    version: str
    config_dir: Path
    data_dir: Path
    luasnip_dir: Path | None
    manager: str | None

    @property
    def name(self) -> str:
        return f"nvim {self.version}"

    @property
    def detail(self) -> str | None:
        return None

    @property
    def jsregexp_installed(self) -> bool:
        if not self.luasnip_dir:
            return False
        return any(
            (self.luasnip_dir / rel).exists()
            for rel in ("deps/luasnip-jsregexp.so", "lua/luasnip-jsregexp.so")
        )

    @property
    def loader_file(self) -> Path:
        return self.config_dir / "plugin" / "snipsmith.lua"

    @property
    def default_snippets_dir(self) -> Path:
        return self.config_dir / "snipsmith"

    def status(self) -> str:
        parts = []
        if self.luasnip_dir:
            parts.append("luasnip installed")
            parts.append("jsregexp installed" if self.jsregexp_installed else "jsregexp not built")
        else:
            parts.append("luasnip not installed")
        if self.manager:
            parts.append(f"plugin manager: {self.manager}")
        return ", ".join(parts)

    def write_loader(self, snippets_dir: Path) -> Path:
        self.loader_file.parent.mkdir(parents=True, exist_ok=True)
        content = LOADER_TEMPLATE.replace("{snippets_dir}", lua_quote(str(snippets_dir)))
        self.loader_file.write_text(content, encoding="utf-8")
        return self.loader_file

    def loader_is_ours(self) -> bool:
        try:
            return LOADER_MARKER in self.loader_file.read_text(encoding="utf-8")
        except OSError:
            return False

    def install(self) -> str:
        """build luasnip's jsregexp extra."""
        if not self.luasnip_dir:
            raise EditorError("luasnip is not installed")
        for tool in ("make", "cc"):
            if not shutil.which(tool):
                raise EditorError(
                    f"`{tool}` is required to build jsregexp; install a c toolchain "
                    f"(on macos: xcode-select --install) and rerun"
                )
        result = subprocess.run(
            ["make", "-C", str(self.luasnip_dir), "install_jsregexp"],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise EditorError(f"jsregexp build failed:\n{(result.stderr or result.stdout).strip()}")
        return "built jsregexp"


def _version(executable: str) -> str:
    try:
        out = subprocess.run(
            [executable, "--version"], capture_output=True, text=True, timeout=10
        ).stdout
    except (OSError, subprocess.TimeoutExpired):
        return "?"
    first = out.splitlines()[0] if out else ""
    return first.replace("NVIM", "").strip() or "?"


def find_luasnip(config_dir: Path, data_dir: Path) -> Path | None:
    patterns = [
        (data_dir, "lazy/LuaSnip"),
        (data_dir, "site/pack/*/*/LuaSnip"),
        (data_dir, "site/pack/*/*/luasnip"),
        (data_dir, "site/pack/*/*/LuaSnip.nvim"),
        (config_dir, "plugged/LuaSnip"),
        (data_dir, "plugged/LuaSnip"),
        (data_dir, "*/LuaSnip"),
    ]
    for base, pattern in patterns:
        for candidate in sorted(base.glob(pattern)):
            if (candidate / "lua/luasnip/init.lua").exists():
                return candidate
    return None


def detect_manager(config_dir: Path, data_dir: Path) -> str | None:
    checks = [
        ("lazy.nvim", data_dir / "lazy/lazy.nvim"),
        ("packer.nvim", data_dir / "site/pack/packer"),
        ("mini.deps", data_dir / "site/pack/deps"),
        ("vim-plug", data_dir / "site/autoload/plug.vim"),
        ("vim-plug", config_dir / "autoload/plug.vim"),
        ("vim.pack", config_dir / "nvim-pack-lock.json"),
        ("vim.pack", data_dir / "site/pack/core"),
    ]
    return next((name for name, path in checks if path.exists()), None)


INSTALL_HINTS = {
    "lazy.nvim": """add to your lazy.nvim plugin specs:
  { "L3MON4D3/LuaSnip", build = "make install_jsregexp" }""",
    "packer.nvim": """add to your packer startup function:
  use({ "L3MON4D3/LuaSnip", run = "make install_jsregexp" })""",
    "mini.deps": """add to your mini.deps config:
  MiniDeps.add({ source = "L3MON4D3/LuaSnip", hooks = { post_install = function(p) vim.system({ "make", "-C", p.path, "install_jsregexp" }):wait() end } })""",
    "vim-plug": """add to your vim-plug block, then run :PlugInstall:
  Plug 'L3MON4D3/LuaSnip', { 'do': 'make install_jsregexp' }""",
    "vim.pack": """add to your init.lua:
  vim.pack.add({ "https://github.com/L3MON4D3/LuaSnip" })
then rerun `snipsmith init` to build jsregexp""",
}
FALLBACK_HINT = (
    "install https://github.com/L3MON4D3/LuaSnip with your plugin manager, then rerun "
    "`snipsmith init` to build jsregexp"
)


def install_hint(manager: str | None) -> str:
    return INSTALL_HINTS.get(manager, FALLBACK_HINT)


def std_paths() -> tuple[Path, Path]:
    """nvim's stdpath("config") and stdpath("data")."""
    appname = os.environ.get("NVIM_APPNAME", "nvim")
    if sys.platform == "win32":
        local = Path(os.environ.get("LOCALAPPDATA") or Path.home() / "AppData/Local")
        return local / appname, local / f"{appname}-data"
    return xdg_config_home() / appname, xdg_data_home() / appname


def detect() -> list[Neovim]:
    executable = shutil.which("nvim")
    if not executable:
        return []
    config_dir, data_dir = std_paths()
    return [
        Neovim(
            version=_version(executable),
            config_dir=config_dir,
            data_dir=data_dir,
            luasnip_dir=find_luasnip(config_dir, data_dir),
            manager=detect_manager(config_dir, data_dir),
        )
    ]
