import pytest

from snipsmith.cli import main
from snipsmith.config import Config


def run(*argv):
    with pytest.raises(SystemExit) as info:
        main(list(argv))
    return info.value.code


def test_check_and_build_to_out_dir(fake_home, repo_snippets, tmp_path, capsys):
    assert run("check", str(repo_snippets)) == 0
    out = tmp_path / "out"
    assert run("build", str(repo_snippets), "--out", str(out)) == 0
    assert sorted(p.name for p in out.iterdir()) == [
        "latex.hsnips",
        "obsidian_snippets.js",
        "obsidian_variables.json",
        "tex.lua",
    ]
    assert run("build", str(repo_snippets), "--out", str(out)) == 0
    assert "4 files, 0 changed" in capsys.readouterr().out


def test_build_uses_config(fake_home, repo_snippets, capsys):
    cfg = Config(snippets=repo_snippets)
    cfg.outputs["neovim"].append(fake_home / "nvim/tex.lua")
    cfg.save()
    assert run("build") == 0
    assert (fake_home / "nvim/tex.lua").exists()
    assert run("build", "--diff") == 0
    assert "no changes" in capsys.readouterr().out
    assert run("doctor") == 0
    assert run("clean", "--yes") == 0
    assert not (fake_home / "nvim/tex.lua").exists()


def test_build_without_destinations_fails(fake_home, repo_snippets, capsys):
    assert run("build", str(repo_snippets)) == 1
    assert "no output paths configured" in capsys.readouterr().err


def test_invalid_source_fails(fake_home, tmp_path, capsys):
    bad = tmp_path / "bad.yaml"
    bad.write_text("snippets:\n  - trigger: ''\n    replacement: x\n")
    assert run("check", str(bad)) == 1
    assert "non-empty string" in capsys.readouterr().err


def test_list_filters(fake_home, repo_snippets, capsys):
    assert run("list", "-f", str(repo_snippets), "pitchfork") == 0
    out = capsys.readouterr().out
    assert out.strip().endswith("1 snippets")


def test_config_path(fake_home, capsys):
    assert run("config", "path") == 0
    assert capsys.readouterr().out.strip() == str(fake_home / ".config/snipsmith/config.toml")


def test_write_through_symlink_keeps_link(fake_home, repo_snippets):
    real_dir = fake_home / "dotfiles"
    real_dir.mkdir()
    (real_dir / "tex.lua").write_text("old")
    link_dir = fake_home / "nvim"
    link_dir.mkdir()
    link = link_dir / "tex.lua"
    link.symlink_to(real_dir / "tex.lua")
    cfg = Config(snippets=repo_snippets)
    cfg.outputs["neovim"].append(link)
    cfg.save()
    assert run("build") == 0
    assert link.is_symlink()
    assert (real_dir / "tex.lua").read_text().startswith("-- generated by snipsmith")


def test_dry_run_and_diff_report_without_writing(fake_home, repo_snippets, capsys):
    cfg = Config(snippets=repo_snippets)
    cfg.outputs["vscode"].append(fake_home / "x/latex.hsnips")
    cfg.save()
    assert run("build", "--dry-run") == 0
    assert "would write" in capsys.readouterr().out
    assert not (fake_home / "x/latex.hsnips").exists()
    assert run("build", "--diff") == 0
    assert "+++ " in capsys.readouterr().out
    assert not (fake_home / "x/latex.hsnips").exists()


def test_doctor_reports_missing_and_stale(fake_home, repo_snippets, capsys):
    cfg = Config(snippets=repo_snippets)
    cfg.outputs["neovim"] += [fake_home / "a/tex.lua", fake_home / "b/tex.lua"]
    cfg.save()
    (fake_home / "a").mkdir()
    (fake_home / "a/tex.lua").write_text("stale")
    assert run("doctor") == 1
    err = capsys.readouterr().err
    assert "stale ~/a/tex.lua" in err
    assert "missing ~/b/tex.lua" in err


def test_edit_rebuilds_and_reports_editor_failure(fake_home, repo_snippets, monkeypatch, capsys):
    cfg = Config(snippets=repo_snippets)
    cfg.outputs["neovim"].append(fake_home / "tex.lua")
    cfg.save()
    monkeypatch.delenv("VISUAL", raising=False)
    monkeypatch.setenv("EDITOR", "true")
    assert run("edit") == 0
    assert (fake_home / "tex.lua").exists()
    monkeypatch.setenv("EDITOR", "false")
    assert run("edit") == 1
    assert "exited with status 1" in capsys.readouterr().err


def test_clean_declined_and_nothing_to_clean(fake_home, repo_snippets, monkeypatch, capsys):
    cfg = Config(snippets=repo_snippets)
    cfg.outputs["neovim"].append(fake_home / "tex.lua")
    cfg.save()
    assert run("build") == 0
    monkeypatch.setattr("snipsmith.ui.confirm", lambda *a, **k: False)
    assert run("clean") == 0
    assert (fake_home / "tex.lua").exists()
    (fake_home / "tex.lua").unlink()
    assert run("clean") == 0
    assert "nothing to clean" in capsys.readouterr().out


def test_config_show_and_edit(fake_home, monkeypatch, capsys):
    assert run("config") == 1
    monkeypatch.delenv("VISUAL", raising=False)
    monkeypatch.setenv("EDITOR", "true")
    assert run("config", "edit") == 0
    assert (fake_home / ".config/snipsmith/config.toml").exists()
    assert run("config") == 0
    assert "[obsidian]" in capsys.readouterr().out


def test_invalid_config_is_a_clean_error(fake_home, capsys):
    path = fake_home / ".config/snipsmith/config.toml"
    path.parent.mkdir(parents=True)
    path.write_text("snippets = [oops\n")
    assert run("check") == 1
    assert "invalid config" in capsys.readouterr().err


def test_missing_source_and_bad_platform(fake_home, capsys):
    assert run("check", str(fake_home / "nope.yaml")) == 1
    assert "not found" in capsys.readouterr().err
    assert run("init", "--only", "emacs") == 2


def test_explicit_config_flag(fake_home, repo_snippets, tmp_path, capsys):
    cfg_path = tmp_path / "alt.toml"
    cfg = Config(snippets=repo_snippets)
    cfg.outputs["neovim"].append(tmp_path / "tex.lua")
    cfg.save(cfg_path)
    assert run("-c", str(cfg_path), "build") == 0
    assert (tmp_path / "tex.lua").exists()
    capsys.readouterr()
    assert run("-c", str(cfg_path), "config", "path") == 0
    assert capsys.readouterr().out.strip() == str(cfg_path)


def test_list_platform_view_and_no_match(fake_home, repo_snippets, capsys):
    assert run("list", "-f", str(repo_snippets), "-p", "vscode") == 0
    out = capsys.readouterr().out
    assert out.strip().endswith("snippets") and "VISUAL" not in out
    assert run("list", "-f", str(repo_snippets), "zzzznotasnippet") == 0
    assert "no matching snippets" in capsys.readouterr().out


def test_warnings_only_source_passes(fake_home, tmp_path, capsys):
    path = tmp_path / "s.yaml"
    path.write_text("snippets:\n  - trigger: a\n    replacement: '[[0]]'\n")
    assert run("check", str(path)) == 0
    assert "not a regex" in capsys.readouterr().err
